### ISSUE TITLE
is the config file you provide the optimal parameter??

### ISSUE THREAD

**Issue by Lee-zix** [shehzaadzd/MINERVA#10]
Thanks for reading my question!
is the config file you provide the optimal parameter?? I run a experiment on the dataset FB15K-237 with the default config file your provide . the results seems a lot different from the result in your paper?This is my result:
INFO:root:Hits@1:  0.1069
04/29/2018 12:23:52 AM: [ Hits@1:  0.1069 ]
INFO:root:Hits@3:  0.1904
04/29/2018 12:23:52 AM: [ Hits@3:  0.1904 ]
INFO:root:Hits@5:  0.2314
04/29/2018 12:23:52 AM: [ Hits@5:  0.2314 ]
INFO:root:Hits@10:  0.2864
04/29/2018 12:23:52 AM: [ Hits@10:  0.2864 ]
INFO:root:Hits@20:  0.3413
04/29/2018 12:23:52 AM: [ Hits@20:  0.3413 ]
INFO:root:auc:  0.1655
04/29/2018 12:23:52 AM: [ auc:  0.1655 ]
Could you help me to reproduce the result of your paper??

**Comment by shehzaadzd** [comment]
Hey, thanks for pointing this out. Let me check and get back to you!
-S

**Comment by Lee-zix** [comment]
Thanks for your timely reply. I am looking forward to your check result and it will help a lot to me, another question. What dose the dummy relation mean in your code. I am confused about the code where the 'dummy, dummy_scores' appeared ,i.e what the code(agent.py)  below used to do??
       ```
        comparison_tensor = tf.ones_like(next_relations, dtype=tf.int32) * self.rPAD  # matrix to compare
        mask = tf.equal(next_relations, comparison_tensor)  # The mask
        dummy_scores = tf.ones_like(prelim_scores) * -99999.0  # `the base matrix to choose from if dummy relation`
        scores = tf.where(mask, dummy_scores, prelim_scores)  # [B, MAX_NUM_ACTIONS]
```
Thanks very much for helping me!!!

**Comment by Lee-zix** [comment]
Thanks for your timely reply. I am looking forward to your check result and it will help a lot to me, another question. What dose the dummy relation mean in your code. I am confused about the code where the 'dummy, dummy_scores' appeared ,i.e what the code(agent.py) below used to do??
```
comparison_tensor = tf.ones_like(next_relations, dtype=tf.int32) * self.rPAD    // matrix to compare
mask = tf.equal(next_relations, comparison_tensor)             //The mask
dummy_scores = tf.ones_like(prelim_scores) * -99999.0     //the base matrix to choose from if dummy relation
scores = tf.where(mask, dummy_scores, prelim_scores) 
```
Thanks very much for helping me!!!

**Comment by shehzaadzd** [comment]
Hey,
The dummy scores are just scores assigned for PAD actions/edges as we do not want our agent to take those actions.
I am able to reproduce the scores at my end for FB15k-237. I just realized that the code was printing some extraneous results due to some debug code which I forgot to remove before pushing.  Could you share the log file generated?

**Comment by Lee-zix** [comment]
Thanks a lot for your reply,I have reproduced the result for FB15k-237 with your help  ! Thanks again for your timely reply and kindly help, great job!

**Comment by shehzaadzd** [comment]
Thanks! :)
-S

**Comment by posenhuang** [comment]
Hi @Lee-zix, is there anything fixes to reproduce the results?

**Comment by David-Lee-1990** [comment]
Is this problem solved?
