### ISSUE TITLE
grid-world dataset access

### ISSUE THREAD

**Issue by posenhuang** [shehzaadzd/MINERVA#11]
Hi @rajarshd, @shehzaadzd,

When I access the grid world data, I got the following error. I am using git-lfs version 1.2. 
```
git lfs fetch --all
Scanning for all objects ever referenced...
* 26 objects found
Fetching objects...
Git LFS: (0 of 26 files, 26 skipped) 0 B / 6.34 MB, 6.34 MB skipped
[404] Object does not exist on the server
[e16e1d42fbd288e20d73337bbce88b29e1d889cfb409de87b87a7d3d3b3c06e5] Object does not exist on the server 
```
Thanks!

**Comment by shehzaadzd** [comment]
Hi, 
The datasets are no longer on the the lfs. You could just do a git pull and should be able to access them.
-S

**Comment by posenhuang** [comment]
Hi @shehzaadzd,

I cannot access them even after git pull. The data only contains: 
```
version https://git-lfs.github.com/spec/v1
oid sha256:e124b2abb404df6e3db477e47ddf8c91aac3d258950ed38a75a35f061897d9c9
size 598469
```

**Comment by shehzaadzd** [comment]
Can you clone a fresh copy? When I git clone, it downloads the datasets.

**Comment by shehzaadzd** [comment]
Tell me if this doesn't work. I can email you the datasets for now.

**Comment by posenhuang** [comment]
Got the dataset through email.
