### ISSUE TITLE
Reproduce WN18RR results

### ISSUE THREAD

**Issue by FredericGodin** [shehzaadzd/MINERVA#17]
I am trying to reproduce the results of WN18RR.
I obtain much lower results despite using the predefined configs.

INFO:root:Hits@1:  0.3500
07/26/2018 02:40:17 PM: [ Hits@1:  0.3500 ]
INFO:root:Hits@3:  0.4346
07/26/2018 02:40:17 PM: [ Hits@3:  0.4346 ]

In the paper Hits@1 is 0.413 and Hits@3 0.456

Moreover, in a new paper they are claiming a sota result compared to these lower results which makes this very confusing...
https://arxiv.org/pdf/1802.04394.pdf

**Comment by FredericGodin** [comment]
Wow this is really confusing, I toyed around with some hyperparas and now I get sota results...

INFO:root:Hits@1:  0.4355
07/26/2018 03:39:47 PM: [ Hits@1:  0.4355 ]
INFO:root:Hits@3:  0.4789
07/26/2018 03:39:47 PM: [ Hits@3:  0.4789 ]
INFO:root:Hits@5:  0.4984
07/26/2018 03:39:47 PM: [ Hits@5:  0.4984 ]
INFO:root:Hits@10:  0.5351
07/26/2018 03:39:47 PM: [ Hits@10:  0.5351 ]

**Comment by shehzaadzd** [comment]
Sorry for the delayed reply. I had not updated the latest hyperparameters to the code. Maybe that's why the initial results were suboptimal. I'll find the correct hyperparameters and update the code. 
Thanks for pointing this out!

**Comment by FredericGodin** [comment]
Hi thanks!

Could you please also comment on the paper I am referencing? 
They claim superior performance over your solution but a referencing the numbers of your default configs...

**Comment by shehzaadzd** [comment]
Can you give me the hyperparameters you ran the code with?

**Comment by FredericGodin** [comment]
I have sent you an e-mail with the full config.
However, I would like to know the hyperparas that gave you the results mentioned in the paper.

**Comment by shehzaadzd** [comment]
WN18RR config corrected. Results now reproducing.

**Comment by David-Lee-1990** [comment]
What is the correct config?
