### ISSUE TITLE
Question in code/model/trainer.py

### ISSUE THREAD

**Issue by BeerTai** [shehzaadzd/MINERVA#23]
Hi, I read your paper and codes and there is a confusion.
in trainer.py, What does ”new_scores = test_scores + beam_probs“ mean?
Why not use 'test_scores' or 'beam_probs' directly?

Thanks~

https://github.com/shehzaadzd/MINERVA/blob/f7060812b26f9c454ac9968520a6124f1be5e644/code/model/trainer.py#L338

**Comment by shehzaadzd** [comment]
Hey,
In a step of the beam search, `beam_probs` holds the **scores** for the elements in the current beam head. `test_scores` has the scores of the next elements. So when the next elements are added to the beam, the `new_scores` hold these scores. You can notice that at the end of the loop that `beam_probs` is set to the scores of the next chosen elements. https://github.com/shehzaadzd/MINERVA/blob/f7060812b26f9c454ac9968520a6124f1be5e644/code/model/trainer.py#L357
