### ISSUE TITLE
num_rollouts

### ISSUE THREAD

**Issue by msaebi** [shehzaadzd/MINERVA#24]
Hi,
I'm getting the following error:

`File ".../grapher.py", line 65, in return_next_actions
    if entities[j] in all_correct_answers[i/rollouts] and entities[j] != correct_e2:
TypeError: list indices must be integers or slices, not float`

This function is called in environment.py:

`next_actions = self.grapher.return_next_actions(self.current_entities, self.start_entities, self.query_relation,self.end_entities, self.all_answers, self.current_hop == self.path_len - 1,self.num_rollouts)`

I wonder what the value of `num_rollouts` should be to prevent `i/rollouts` to become a float (as far as I see, `i` is already an integer.

**Comment by yifding** [comment]
I met the same issue and it can be fixed by changing the i/rollouts to int(i/rollouts)

**Comment by shehzaadzd** [comment]
@msaebi ; the code was written in Python 2.7. You would need to make a few changes to run in Python 3.
