### ISSUE TITLE
Pytorch implementation for MINERVA

### ISSUE THREAD

**Issue by ty4b112** [shehzaadzd/MINERVA#29]
Thanks for your code.

I want to implement MINERVA with pytorch further research.  I implemented my own version according to your source code, but unfortunately I couldn't achieve the similar results as yours.

My implementation is available at  https://github.com/ty4b112/pytorch_MINERVA. It will be very helpful if someone use my code and find why my implementation is worse than the original version or provide another pytorch implementation with better performance.

**Comment by chrislouis0106** [comment]
@ty4b112 
hi, as you said, I try to use your code. However, when I try to read your code, I found it's messy and no interpretation. So, if you could give some introduce your code and give some introduction to the code module.
Thank you very much!
