### ISSUE TITLE
Do you think KG can solve this kind of question?

### ISSUE THREAD

**Issue by guotong1988** [shehzaadzd/MINERVA#6]
1,
A lives in C. `(A, liveInCity, C)`
B lives in C. `(B, liveInCity, C)`
Does A and B live in the same city?

2,
A is 180 cm height. `(A, height, 180)`
B is 175 cm height. `(B, height, 175)`
Is B taller than A?

Thank you very much.

**Comment by shehzaadzd** [comment]
Hi,
We have not tested our model currently on a dataset which has such kind of questions. For the second type we will have to equip our model with some mathematical operators. This is an interesting direction for our work and would love to further discuss this over email!
-S

**Comment by guotong1988** [comment]
Thank you for your reply.
I am also thinking about the solution..
Which way do you think is better for these questions? 
1, Adding more information into the graph;
2, The semantic parsing way;
3, Equip the model with some mathematical operators.
Thank you very much.
