### ISSUE TITLE
Dataset Inconsistency

### ISSUE THREAD

**Issue by RamonYeung** [shehzaadzd/MINERVA#8]
This dataset contains two files for training and the #lines doesn't add up. 

https://github.com/shehzaadzd/MINERVA/tree/master/datasets/data_preprocessed/countries_S3

Can you please replace it with origin dataset or just leave a link/path to the origin?

Thank you.

BTW, great work!

**Comment by shehzaadzd** [comment]
Hey,

The model trains on both train.txt and graph.txt. It learns to find equivalent relations for the ones in train by walking on the graph. Usually, we keep train and graph to be the same. But we noticed that it trained faster on the countries task when we only trained on the located_in relation as this is the relation the model needed to find equivalent relations for. The model still learns to walk on the same graph but only uses a smaller subset of the train to learn equivalent relations.
Sorry for the confusion. I'll make it clear in the readme.
Thanks
-S
